@apil=http://localhost:8000

###
GET {{apil}}/health

###
# @name auth
POST {{apil}}/api/user/c/signin
Content-Type: application/json

{
  "login": "user01",
  "password": "pass01"
}

@token = {{auth.response.body.auth_token}}

###
POST {{apil}}/api/recipe/c/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Tom Collins",
  "description": "The Tom Collins is a classic summer highball that's perfect for the golf course or a backyard barbecue, made from gin, lemon juice, simple syrup, and club soda. The Tom Collins is served in, you guessed it, a Collins glass, which is narrower than a typical highball. A nice side effect of this glassware is that when you tilt the drink all the way back to get those last few drops, the ice is a lot less likely to spill down the front of your shirt. But hey, come July, that might not be so bad!The origins of the Tom Collins recipe is a bit murky, but it seems likely that it was invented in England sometime in the early 19th century. That said, the Tom Collins cocktail first appeared in print in the 1876 edition of American barman Jerry Thomas' How to Mix Drinks.For a quick changeup, use vodka in place of gin, and you get the easygoing Vodka Collins.",
  "ingredients": [
    "2 oz gin",
    "1 oz lemon juice",
    "0.25 oz simple syrup",
    "Club soda",
    "Maraschino cherry and lemon slice for garnish"
  ],
  "steps": [
    {
      "Title": "Add the gin, lemon juice, and simple syrup to a Collins glass filled with ice.",
      "Time": 10
    },
    {
      "Title": "Stir.",
      "Time": 20
    },
    {
      "Title": "Fill the rest of the class with club soda.",
      "Time": 45
    },
    {
      "Title": "Garnish with a cherry and lemon slice and serve.",
      "Time": 15
    }
  ]
}

###
POST {{apil}}/api/recipe/c/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "07f70d64-1a70-11ee-bc17-047c165324e7",
  "title": "Tom Collins123",
  "description": "The Tom Collins is a classic summer highball that's perfect for the golf course or a backyard barbecue, made from gin, lemon juice, simple syrup, and club soda. The Tom Collins is served in, you guessed it, a Collins glass, which is narrower than a typical highball. A nice side effect of this glassware is that when you tilt the drink all the way back to get those last few drops, the ice is a lot less likely to spill down the front of your shirt. But hey, come July, that might not be so bad!The origins of the Tom Collins recipe is a bit murky, but it seems likely that it was invented in England sometime in the early 19th century. That said, the Tom Collins cocktail first appeared in print in the 1876 edition of American barman Jerry Thomas' How to Mix Drinks.For a quick changeup, use vodka in place of gin, and you get the easygoing Vodka Collins.",
  "ingredients": [
    "2 oz gin",
    "1 oz lemon juice",
    "0.25 oz simple syrup",
    "Club soda",
    "Maraschino cherry and lemon slice for garnish"
  ],
  "steps": [
    {
      "title": "Add the gin, lemon juice, and simple syrup to a Collins glass filled with ice.",
      "time": 10
    },
    {
      "title": "Stir.",
      "time": 20
    },
    {
      "title": "Fill the rest of the class with club soda.",
      "time": 45
    },
    {
      "title": "Garnish with a cherry and lemon slice and serve.",
      "time": 15
    }
  ],
  "total_time": 0
}

###
POST {{apil}}/api/recipe/c/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Tom Collins",
  "description": "The Tom Collins is a classic summer highball that's perfect for the golf course or a backyard barbecue, made from gin, lemon juice, simple syrup, and club soda. The Tom Collins is served in, you guessed it, a Collins glass, which is narrower than a typical highball. A nice side effect of this glassware is that when you tilt the drink all the way back to get those last few drops, the ice is a lot less likely to spill down the front of your shirt. But hey, come July, that might not be so bad!The origins of the Tom Collins recipe is a bit murky, but it seems likely that it was invented in England sometime in the early 19th century. That said, the Tom Collins cocktail first appeared in print in the 1876 edition of American barman Jerry Thomas' How to Mix Drinks.For a quick changeup, use vodka in place of gin, and you get the easygoing Vodka Collins.",
  "ingredients": [
    "2 oz gin",
    "1 oz lemon juice",
    "0.25 oz simple syrup",
    "Club soda",
    "Maraschino cherry and lemon slice for garnish"
  ],
  "steps": [
    {
      "Title": "Add the gin, lemon juice, and simple syrup to a Collins glass filled with ice.",
      "Time": 10
    },
    {
      "Title": "Stir.",
      "Time": 20
    },
    {
      "Title": "Fill the rest of the class with club soda.",
      "Time": 45
    },
    {
      "Title": "Garnish with a cherry and lemon slice and serve.",
      "Time": 15
    }
  ],
  "total_time": 120
}

###
POST {{apil}}/api/recipe/c/delete
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": "24556a96-1a70-11ee-bc17-047c165324e7"
}

###
POST {{apil}}/api/recipe/q/list
Content-Type: application/json

{
}

###
POST {{apil}}/api/recipe/q/read
Content-Type: application/json

{
    "id": "e3ba3b81-1a6e-11ee-a87e-047c165324e7"
}

###
POST {{apil}}/api/recipe/c/vote
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "recipe_id": "e3ba3b81-1a6e-11ee-a87e-047c165324e7",
    "mark": 5
}

###
POST {{apil}}/api/recipe/q/find
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "ingredients": [
    "2 oz gin",
    "Club soda"
  ],
  "max_time": 160,
  "sort_by_time": "asc",
  "min_rating": 3,
  "sort_by_rating": "desc"
}
