// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/gorilla/mux"
)

// Id defines model for Id.
type Id struct {
	Id openapi_types.UUID `json:"id"`
}

// Recipe defines model for Recipe.
type Recipe struct {
	Description string   `json:"description"`
	Ingredients []string `json:"ingredients"`
	Steps       []string `json:"steps"`
	Title       string   `json:"title"`
}

// RecipeWithId defines model for RecipeWithId.
type RecipeWithId struct {
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	Ingredients []string           `json:"ingredients"`
	Steps       []string           `json:"steps"`
	Title       string             `json:"title"`
}

// Recipes defines model for Recipes.
type Recipes struct {
	Items *[]RecipeWithId `json:"items,omitempty"`
}

// PostApiRecipeCCreateJSONRequestBody defines body for PostApiRecipeCCreate for application/json ContentType.
type PostApiRecipeCCreateJSONRequestBody = Recipe

// PostApiRecipeCDeleteJSONRequestBody defines body for PostApiRecipeCDelete for application/json ContentType.
type PostApiRecipeCDeleteJSONRequestBody = Id

// PostApiRecipeCUpdateJSONRequestBody defines body for PostApiRecipeCUpdate for application/json ContentType.
type PostApiRecipeCUpdateJSONRequestBody = RecipeWithId

// PostApiRecipeQReadJSONRequestBody defines body for PostApiRecipeQRead for application/json ContentType.
type PostApiRecipeQReadJSONRequestBody = Recipe

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create recipe
	// (POST /api/recipe/c/create)
	PostApiRecipeCCreate(w http.ResponseWriter, r *http.Request)
	// Update recipe
	// (POST /api/recipe/c/delete)
	PostApiRecipeCDelete(w http.ResponseWriter, r *http.Request)
	// Update recipe
	// (POST /api/recipe/c/update)
	PostApiRecipeCUpdate(w http.ResponseWriter, r *http.Request)
	// List recipes
	// (POST /api/recipe/q/list)
	PostApiRecipeQList(w http.ResponseWriter, r *http.Request)
	// Read recipe
	// (POST /api/recipe/q/read)
	PostApiRecipeQRead(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// PostApiRecipeCCreate operation middleware
func (siw *ServerInterfaceWrapper) PostApiRecipeCCreate(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiRecipeCCreate(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PostApiRecipeCDelete operation middleware
func (siw *ServerInterfaceWrapper) PostApiRecipeCDelete(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiRecipeCDelete(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PostApiRecipeCUpdate operation middleware
func (siw *ServerInterfaceWrapper) PostApiRecipeCUpdate(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiRecipeCUpdate(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PostApiRecipeQList operation middleware
func (siw *ServerInterfaceWrapper) PostApiRecipeQList(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiRecipeQList(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PostApiRecipeQRead operation middleware
func (siw *ServerInterfaceWrapper) PostApiRecipeQRead(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiRecipeQRead(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshallingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshallingParamError) Error() string {
	return fmt.Sprintf("Error unmarshalling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshallingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/api/recipe/c/create", wrapper.PostApiRecipeCCreate).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/recipe/c/delete", wrapper.PostApiRecipeCDelete).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/recipe/c/update", wrapper.PostApiRecipeCUpdate).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/recipe/q/list", wrapper.PostApiRecipeQList).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/recipe/q/read", wrapper.PostApiRecipeQRead).Methods("POST")

	return r
}
